### ISSUE TITLE
Editor name used instead of author name in autogenerated key

### ISSUE THREAD

**Issue by brabalan** [joostkremers/ebib#79]
When I edit the following using ebib
```
type                InProceedings

author              Grigore Ro{\,s}u
title               Matching Logic - Extended Abstract (Invited Talk)
year                2015
date                
booktitle           26th International Conference on Rewriting Techniques and Applications, RTA 2015

editor              Maribel Fernández
volume              36
series              LIPIcs
number              
note                
organization        
publisher           Schloss Dagstuhl - Leibniz-Zentrum fuer Informatik
pages               5--21
```

I get the wrong name in the autogenerated key: it's using Fernández instead of Rosu. Here is the bib file:
```
@InProceedings{Fernández2015,
	pages = {5--21},
	publisher = {Schloss Dagstuhl - Leibniz-Zentrum fuer Informatik},
	series = {LIPIcs},
	volume = {36},
	editor = {Maribel Fernández},
	booktitle = {26th International Conference on Rewriting Techniques and Applications, RTA 2015},
	year = {2015},
	title = {Matching Logic - Extended Abstract (Invited Talk)},
	author = {Grigore Ro{\,s}u}
}
```

For some reason the editor name is present before the author name. Could it explain why the author name is not picked first?

**Comment by joostkremers** [comment]
Yes, I can confirm the problem and it seems it’s indeed caused by the fact that the editor appears first in the entry. I’ll have to think a bit about the best way to fix it. I’ll post here when I come up with a fix.

**Comment by joostkremers** [comment]
The latest commit should fix the issue. See if it works and let me know if you run into any problems.

Note, though, that `bibtex-generate-autokey` doesn't seem to recognize `Ro{\,s}u` as a valid last name, so it uses `Grigore` as name part. I’m not sure how to fix this, though.

**Comment by brabalan** [comment]
I just tried it (with the Melpa version of July 2nd) and I still see the problem.

**Comment by joostkremers** [comment]
Yes, because I made a mistake when committing... Should be fixed in the latest commit.

**Comment by brabalan** [comment]
It is, thanks a lot!
